name: Cargo audit
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions-rs/audit-check@35b7b53b1e25b55642157ac01b4adceb5b9ebef3 # v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
